### ISSUE TITLE
selectTranslate not available for lazy loaded translations if transloco pipe is not used

### ISSUE THREAD

**Issue by mohamedaarab1994** [ngneat/transloco#207]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

It is not possible to use selectTranslate in conjunction with lazy loaded translations without using the transloco pipe. The scope was specified in the providers, but for some reason it says that the translation key is missing. Also, if you do use the transloco pipe in the HTML, selectTranslate will still not (always) be available when you use it in ngOnInit hook. In the stackblitz below you can see the behavior if you go to `/lazy-typescript-only` page.

https://stackblitz.com/edit/ngneat-transloco-issue

## Expected behavior
selectTranslate should be available even if you don't use the transloco pipe. Sometimes you need to translate strings within typescript without using the transloco pipe. Also selectTranslate returns an observable which should emit the translation once it's available (perhaps wait for the file to be resolved before selectTranslate observable emits the translation). In the current situation the observables emits only one attempt which means that if the translation is not available at the time of subscribing, it will show a missing key warning.

## Minimal reproduction of the problem with instructions

If you open the stackblitz:

https://stackblitz.com/edit/ngneat-transloco-issue

You can go to /lazy-typescript-only and if you look at the console you see the missing key warning while the file was specified in the module. If you uncomment the html snippet in the lazy-typescript-only component, you will see that the translation is available, but ONLY when you press the button.

## What is the motivation / use case for changing the behavior?

To make this library better and bug-free

## Environment

<pre><code>
Angular version: 7

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ArielGueta** [comment]
You are using the wrong syntax. In typescript, it should be `selectTranslate('title', {}, 'lazy-page')`

**Comment by mohamedaarab1994** [comment]
@ArielGueta Ahh I see, my bad then. The third param name was called `lang`. I thought you were only able to pass a language code as parameter then such as 'en' or 'es'. Thanks, you saved me!

**Comment by mohamedaarab1994** [comment]
@ArielGueta I just tried it in my own projects, but that doesn't seem to work like you say. I can only get the translations after a while (after DOM render). I tested this on a function that is attached to a click event:

```  public click() {
    this._translocoService.selectTranslateObject('PhoneNumberInput.Countries').subscribe(x => console.log(x));
    this._translocoService.selectTranslateObject('Countries', {}, 'features/phone-number-input').subscribe(x => console.log(x));
  }```

The first selectTranslateObject works in a click event, but not in ngOnInit or the constructor.
The second selectTranslateObject never works, not even after the file was loaded in.

It seems like it doesn't re-emit when the translation is available. It just spits out undefined once. Could it be that the file size (about 225 lines) of the json file is the cause of the network lag?

**Comment by ArielGueta** [comment]
can you update the stackblitz?

**Comment by mohamedaarab1994** [comment]
@ArielGueta I just updated the stackblitz. You can find it in lazy-typescript-only. I can tell it has something to do with network latency, because you rarely get a value back on ngOnInit if you refresh a couple of times.

**Comment by ArielGueta** [comment]
Why do you keep using     `this._translocoService.selectTranslateObject('PhoneNumberInput.Countries').subscribe(x => console.log(x));`?

It's not the correct syntax.

**Comment by mohamedaarab1994** [comment]
@ArielGueta I used the syntax you gave me and that didn't work at all for me. The one you just mentioned only works in a click event (meaning that the json file was ready at the time of clicking)

**Comment by shaharkazaz** [comment]
You guys are both right 🙂 
@mohamedaarab1994 The syntax that @ArielGueta said is the correct one, but there was a bug related to loading scopes using the selectTranslateObject (which is now fixed in v2.12.2).

Thanks for the report and the help, Merry Christmas 🎄 and Happy Hanukkah! 🕎

**Comment by rmcsharry** [comment]
@ArielGueta @shaharkazaz It seems this is not fixed, I am experiencing this in version 2.14.

selectTranslate() does not emit during component initialisation

**Comment by rmcsharry** [comment]
Ok, my apologies, we are using scoped files (not one huge file) for translations, so if I provide the scope in the call

    this.translocoService
      .selectTranslate(key, {}, 'testimonials')
      .subscribe(result => {
        console.log(result);
		})

then it works fine.

**Comment by kmihaly** [comment]
@rmcsharry I am really grateful for your previous answer, since it saved us a lot of work hours. The documentation regarding this function is...well...it should be revised and completed :(

**Comment by shaharkazaz** [comment]
@kmihaly you are always welcome to open a pr and change the things you find missing :)

**Comment by bitforcesrl** [comment]
Hi all,
I keep having the same problem, the scoped translations are not loaded when calling the selectTranslate.

```
this.transloco
.selectTranslate('COMMON.LANGUAGE', {}, { scope: 'app' })
.subscribe((res) => {
  console.log(res);
});
```
I'm receiving  `Missing translation for 'app.COMMON.LANGUAGE'`

If I use the transloco pipe everything works.
Angular 16.2.0 and transloco 6.0.4

Thank you

**Comment by shaharkazaz** [comment]
@bitforcesrl First, I encourage you to update to the latest version, ' 7.4.1` under the `@jsverse` scope.
I've tested the selectTranslate scope functionality in the playgrounds and didn't encounter what you are experiencing.
Please open a new issue with a reproduction link so I can address the issue.
